apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30443
# This line generated the error: The Service "nginx-ingress" is invalid: spec.ports[0].nodePort: Invalid value: 443: provided port is not in the valid range. The range of valid ports is 30000-32767
#    nodePort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
