apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  host: api.test.dataone.org
  upstreams:
  - name: metadig-controller
    service: metadig-controller
    port: 8080
  subroutes:
  - path: /quality
    action:
      pass: metadig-controller
