apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nceas
  namespace: nginx-ingress
spec:
  host: api.test.dataone.org
  #host: docker-dev-ucsb-1.test.dataone.org
  tls:
    #secret: metadig-tls-cert
    secret: nginx-ingress-tls-cert
  routes:
  - path: /quality
    route: metadig/metadig-controller
  - path: /bookkeeper
    route: bookkeeper/bookkeeper
